eureka:
  client:
    serviceUrl:
      defaultZone: http://zhaoxin1:zhaoxin1@192.168.86.250:8761/eureka/
  instance:
    ip-address: 192.168.0.105
    prefer-ip-address: true
    instance-id: ${eureka.instance.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 30    lease-renewal-interval-in-seconds: 15
server:
  port: 8764
spring:
  application:
    name: springcloud-ribbon-server
  zipkin:    base-url: http://192.168.86.250:9411
    
    
#springcloud-eureka-client:
#  ribbon:
#    NFLoadBalancerRuleClassName:com.netflix.loadbalancer.RandomRule 



    
